<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: 'Helvetica', sans-serif;
            font-size: 12px;
            color: #333;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #1f7a2d;
            padding-bottom: 10px;
        }

        .header h1 {
            color: #1f7a2d;
            margin: 0;
            font-size: 24px;
        }

        .header p {
            margin: 5px 0;
            color: #666;
        }

        .meta {
            margin-bottom: 20px;
        }

        .meta table {
            width: 100%;
        }

        .meta td {
            padding: 5px;
        }

        table.data {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        table.data th,
        table.data td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        table.data th {
            background-color: #f2f2f2;
            color: #1f7a2d;
            font-weight: bold;
        }

        table.data tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #999;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>CMU Guidance and Counseling Center</h1>
        <p>Guidance Module Report</p>
    </div>

    <div class="meta">
        <table>
            <tr>
                <td><strong>Report Type:</strong> {{ $type }}</td>
                <td style="text-align: right;"><strong>Date Generated:</strong> {{ $date }}</td>
            </tr>
            <tr>
                <td><strong>Filters:</strong> Year Level: {{ $filters['Year Level'] }}, Seminar:
                    {{ $filters['Seminar'] }}</td>
                <td style="text-align: right;"><strong>Total Students:</strong> {{ $students->count() }}</td>
            </tr>
        </table>
    </div>

    <table class="data">
        <thead>
            <tr>
                <th>Student Name</th>
                <th>ID Number</th>
                <th>Year Level</th>
                <th>Status</th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody>
            @forelse($students as $student)
                <tr>
                    <td>{{ $student->name }}</td>
                    <td>{{ $student->id_number ?? 'N/A' }}</td>
                    <td>{{ $student->year_level }}</td>
                    <td>{{ $student->status }}</td>
                    <td>{{ $student->details }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" style="text-align: center;">No records found matching the criteria.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by GCC System on {{ now()->format('F j, Y g:i A') }}
    </div>
</body>

</html>